apiVersion: v1
kind: Secret
type: kubebernetes.io/basic-auth
metadata:
  name: keycloak
data:
  username: {{ .Values.administrator.username | b64enc | quote }}
  password: {{ .Values.administrator.password | b64enc | quote }}
