apiVersion: v1
kind: Service
metadata:
  name: keycloak

spec:
  ports:
    - port: 9000
      name: management
    - port: 8080
      name: development
    - port: 8443
      name: production
  type: ClusterIP
  selector:
    name: keycloak
