apiVersion: v2
name: postgrest
version: 0.2.2
description: Helm chart for a PostgREST data api

dependencies:
  - name: cluster
    version: 0.5.0
    repository: https://cloudnative-pg.io/charts/
    condition: cluster.enabled
