apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest

spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgrest
  template:
    metadata:
      labels:
        name: postgrest
    spec:
      initContainers:
        {{ if not (empty .Values.application.jwk.public) }}
        - name: jwks
          image: alpine/curl
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "curl --location {{ .Values.application.jwk.public }} > /etc/opt/postgrest/certificates/jwk.json"
        - volumeMounts:
            - mountPath: /etc/opt/postgrest/certificates
              name: certificates
        {{ end }}
        - name: goose
          image: {{ .Values.database.migrations.image }}:{{ .Values.database.migrations.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/goose
            - {{ .Values.database.migrations.enabled | ternary "up" "status" }}
          env:
            - name: GOOSE_DRIVER
              value: postgres
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  key: connection
                  name: migrations
      containers:
        - name: postgrest
          image: postgrest/postgrest
          imagePullPolicy: IfNotPresent
          env:
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  key: connection
                  name: application
            - name: PGRST_DB_ANON_ROLE
              value: {{ .Values.application.anon }}
            - name: PGRST_DB_SCHEMAS
              value: {{ .Values.application.schemas }}
            - name: PGRST_JWT_ROLE_CLAIM_KEY
              value: {{ .Values.application.jwt.claim.selector }}
            {{ if not (empty .Values.application.jwk.public) }}
            - name: PGRST_JWT_SECRET
              value: "@/etc/opt/postgrest/certificates/jwks.json"
            {{ else }}
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt.secret
                  name: authentication
            {{ end }}
          volumeMounts:
            - mountPath: /etc/opt/postgrest/certificates
              name: certificates
      volumes:
        - name: certificates
          emptyDir:
            sizeLimit: 1Ki
