apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: "{{ .Release.Namespace }}"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: postgrest
    app.kubernetes.io/instance: "{{ .Release.Namespace }}"
    app.kubernetes.io/name: postgrest
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
